// This file is autogenerated please do not edit! See scripts/gen_autoloader.js
#pragma once
#include "registry.h"
#include "01_basic_tracking/basic_tracking.h"
namespace Autoloader {
	void init() {
		TestCaseRegistry::getInstance()->registerTestCase<BasicTrackingTestCase>();
	}
}
